// <auto-generated />
using System;
using Lab6.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab6.Migrations
{
    [DbContext(typeof(EshopsContext))]
    [Migration("20230611225104_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab6.DatabaseContext.Delivery", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<string>("DelAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("DelCost")
                        .HasColumnType("money");

                    b.Property<string>("DelCourier")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("DelDate")
                        .HasColumnType("datetime");

                    b.HasKey("OrderId");

                    b.ToTable("Delivery", (string)null);
                });

            modelBuilder.Entity("Lab6.DatabaseContext.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Lab6.DatabaseContext.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemID");

                    b.Property<int>("OrderCid")
                        .HasColumnType("int")
                        .HasColumnName("OrderCID");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ShopId")
                        .HasColumnType("int")
                        .HasColumnName("ShopID");

                    b.HasKey("OrderId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ShopId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Lab6.DatabaseContext.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShopID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopId"));

                    b.Property<string>("ShopAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShopEmail")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("Lab6.DatabaseContext.ShopItem", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemID");

                    b.Property<int>("ShopId")
                        .HasColumnType("int")
                        .HasColumnName("ShopID");

                    b.HasIndex("ItemId");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopItem", (string)null);
                });

            modelBuilder.Entity("Lab6.DatabaseContext.Delivery", b =>
                {
                    b.HasOne("Lab6.DatabaseContext.Order", "Order")
                        .WithOne("Delivery")
                        .HasForeignKey("Lab6.DatabaseContext.Delivery", "OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_Delivery_Delivery");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Lab6.DatabaseContext.Order", b =>
                {
                    b.HasOne("Lab6.DatabaseContext.Item", "Item")
                        .WithMany("Orders")
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Items");

                    b.HasOne("Lab6.DatabaseContext.Shop", "Shop")
                        .WithMany("Orders")
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Shops");

                    b.Navigation("Item");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Lab6.DatabaseContext.ShopItem", b =>
                {
                    b.HasOne("Lab6.DatabaseContext.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .IsRequired()
                        .HasConstraintName("FK_ShopItem_Items");

                    b.HasOne("Lab6.DatabaseContext.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .IsRequired()
                        .HasConstraintName("FK_ShopItem_Shops");

                    b.Navigation("Item");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Lab6.DatabaseContext.Item", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Lab6.DatabaseContext.Order", b =>
                {
                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("Lab6.DatabaseContext.Shop", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
